---
  # Start the gluster service
  - name: reload systemd daemon
    command: systemctl daemon-reload
  - name: start rpcbind service
    service:
      name: rpcbind.service
      state: started
      enabled: yes
  - name: start glusterd service
    service:
      name: glusterd.service
      state: started
      enabled: yes
    when: ansible_os_family == 'Debian'
  - name: start glusterd service
    service:
      name: glusterd.service
      state: started
      enabled: yes
    when: ansible_os_family == 'RedHat'
  - name: probe peer nodes from the first node
    command: gluster peer probe {{ inventory_hostname }}
    delegate_to: "{{ groups['storage'][0] }}" # Do the probing on the first storage node
    when: groups['storage'] | length > 1 and inventory_hostname != groups['storage'] | first # Do not probe itself
    
  - name: probe the first peer from the last peer
    command: gluster peer probe {{ groups['storage'] | first }}
    delegate_to: "{{ groups['storage'] | last }}"
    run_once: true
    when: groups['storage'] | length > 1