---
  - hosts: master:worker:ingress:storage
    any_errors_fatal: true
    name: Generate Kubectl Config File
    serial: "{{ serial_count | default('100%') }}"
    remote_user: root
    become_method: sudo
    vars_files:
      - group_vars/all.yaml

    pre_tasks:
      - name: delete cluster services kubeconfig
        file:
          path: "{{ kubernetes_services_kubeconfig_path }}"
          state: absent
        when: upgrading is defined and upgrading|bool == true

    roles:
      - kubeconfig
