apiVersion: v1
kind: Pod
metadata:
  labels:
    tier: control-plane
    component: kube-scheduler
    version: "{{ kubernetes_version }}"
    kismaticVersion: "{{ kismatic_short_version }}"
  name: kube-scheduler
  namespace: kube-system
spec:
  hostNetwork: true
  containers:
  - name: kube-scheduler
    image: {{ kube_scheduler_img }}
    imagePullPolicy: IfNotPresent
    command:
      - kube-scheduler
      - --kubeconfig={{ kubernetes_kubeconfig_path }}
      - --leader-elect=true
      - --master={{ kubernetes_master_ip }}
      - --v=2
    volumeMounts:
      - mountPath: "{{ kubernetes_kubeconfig_path }}"
        name: "kubeconfig"
        readOnly: true
      - mountPath: /etc/kubernetes
        name: ssl-certs-kubernetes
        readOnly: true
    livenessProbe:
      httpGet:
        host: 127.0.0.1
        path: /healthz
        port: 10251
      initialDelaySeconds: 15
      timeoutSeconds: 5
  volumes:
    - name: "kubeconfig"
      hostPath:
        path: "{{ kubernetes_kubeconfig_path }}"
    - hostPath:
        path: /etc/kubernetes
      name: ssl-certs-kubernetes
