--- 
  - name: stop glusterd service
    service:
      name: glusterd.service
      state: stopped
    when: ansible_os_family == 'RedHat'
    register: result
    failed_when: "result|failed and ('find' not in result.msg and 'found' not in result.msg)" # make idempotent

  - name: stop glusterd service
    service:
      name: glusterd.service
      state: stopped
      enabled: yes
    when: ansible_os_family == 'Debian'
    register: result
    failed_when: "result|failed and ('find' not in result.msg and 'found' not in result.msg)" # make idempotent

  - name: remove gluster packages
    package: name={{ item }} state=absent
    register: result
    until: result|success
    retries: 2
    delay: 1
    with_items:
      - glusterfs-server
      - glusterfs-client
      - glusterfs-common

  - name: remove gluster yum repository
    yum_repository:
      name: gluster
      description: Gluster 3.13
      baseurl: "http://buildlogs.centos.org/centos/7/storage/x86_64/gluster-3.13/"
      state: absent
    when: ansible_os_family == 'RedHat' and 'storage' in group_names
    environment: "{{proxy_env}}"

  - name: remove gluster deb repository
    apt_repository:
      repo: ppa:gluster/glusterfs-3.13
      state: absent
    when: ansible_os_family == 'Debian' and 'storage' in group_names
    environment: "{{proxy_env}}"